import { Playfair_Display, DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${playfair.variable} ${dmMono.variable} font-sans antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Link href={"https://forms.gle/8gdSTqypVXaV5jgk6"} className="fixed bottom-5 left-1/2 -translate-x-1/2 px-5 py-2 rounded-full text-[#d7ff00] bg-black  border border-[#d7ff00]/50" target="_blank">
          Contact Us
        </Link>
      </body>
    </html>
  );
}
